name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - Lavapipe
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1', 'lts']
    steps:
      - uses: actions/checkout@v4
      - uses: serenity4/julia-lavapipe@v1
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
